const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const CONFLICT = 409;
const INTERNAL_SERVER_ERROR = 500;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const NO_CONTENT = 204;

module.exports = {
  OK,
  CREATED,
  BAD_REQUEST,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED,
  NOT_FOUND,
  NO_CONTENT,
};
